version: 2

jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/ruby:2.5.5

    environment:
      COVALENCE_VERSION: 0.9.0
      TERRAFORM_VERSION: 0.12.6
      SOPS_VERSION: 3.3.1
      BUNDLER_VERSION: 1.17.2

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            # Install Terraform
            wget -q "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
            unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip

            # Install Sops
            sudo wget -q "https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux" -O /usr/local/bin/sops
            sudo chmod +x /usr/local/bin/sops
            # Insstall bundler version in Gemlock before install
            gem install bundler:${BUNDLER_VERSION}
            # Install gem bundle
            bundle install

      - run:
          name: Run tests
          command: bundle exec rake ci:covalence

      - run:
          name: Setup gem credentials
          command: |
            mkdir -p ~/.gem/
            cat <<EOF >~/.gem/credentials
            ---
            :rubygems_api_key: ${RUBYGEMS_API_KEY}
            EOF
            chmod 600 ~/.gem/credentials

      - deploy:
          name: Publish gem to rubygems
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              gem signin
              gem build covalence.gemspec
              COVALENCE_VERSION=$(ruby -e "require \"#{Dir.pwd}/lib/covalence/version\"; puts Covalence::VERSION")
              gem push covalence-${COVALENCE_VERSION}.gem
            fi
