##### Prometheus configuration data #####
#
## Define deployment environments ##
#
environments:
  rspec:
    - myapp:
        state:
          - atlas:
              name: 'example/myapp'
        args: '-no-color'
        vars:
          label: 'test'
        targets:
          az0:
            - 'module.az0'
          az1:
            - 'module.az1'
            - 'module.common.aws_eip.myapp'
    - module_test:
        module: 'myapp2'
        state:
          - atlas:
              name: 'example/myapp'
    - artifact_test:
        module: 'myapp2'
        state:
          - atlas:
              name: 'example/myapp'
        vars:
          label: 'test'
          ami:
            type: 'atlas.artifact'
            slug: 'unifio/aws-linux/amazon.ami'
            version: 1
            metadata: 'region.us-west-2'
